# Generated by Django 4.2 on 2024-05-27 00:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_created_date_alter_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Estados', 'verbose_name_plural': 'estados'},
        ),
        migrations.AddField(
            model_name='city',
            name='id_state',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='user.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='phonecode',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='country',
            name='shortname',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 0, 12, 38, 154601, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 0, 12, 38, 154601, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 0, 12, 38, 154601, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='state',
            table='estados',
        ),
    ]
