# Generated by Django 4.2 on 2024-05-27 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_state_options_city_id_state_country_phonecode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 1, 42, 32, 883436, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 1, 42, 32, 883436, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 1, 42, 32, 883436, tzinfo=datetime.timezone.utc)),
        ),
    ]
