# Generated by Django 4.2 on 2024-06-06 03:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name': 'Vehicle_category',
                'verbose_name_plural': 'vehicle_categories',
                'db_table': 'vehicle_category',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name': 'Vehicle_type',
                'verbose_name_plural': 'vehicle_types',
                'db_table': 'vehicle_type',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country')),
                ('vehicle_categories', models.ManyToManyField(to='vehicles.vehicle_category')),
                ('vehicle_types', models.ManyToManyField(to='vehicles.vehicle_type')),
            ],
            options={
                'verbose_name': 'Vehicle_brand',
                'verbose_name_plural': 'vehicle_brands',
                'db_table': 'vehicle_brand',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True)),
                ('model', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=250)),
                ('fuel_type', models.CharField(choices=[('ELECTRICO', 'ELECTRICO'), ('EXTRA', 'EXTRA'), ('DIESEL', 'DIESEL'), ('GASOLINA', 'GASOLINA'), ('GAS', 'GAS')], default='GASOLINA', max_length=15)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_category')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_type')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'vehicles',
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField()),
                ('last_date', models.DateField(default=django.utils.timezone.now)),
                ('id_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Mileage',
                'verbose_name_plural': 'mileage',
                'db_table': 'mileage',
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_traveled', models.FloatField()),
                ('liters_amount', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.DateField(default=datetime.datetime(2024, 6, 6, 3, 7, 24, 959061, tzinfo=datetime.timezone.utc))),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Consumption',
                'verbose_name_plural': 'consumptions',
                'db_table': 'consumption',
            },
        ),
    ]
