# Generated by Django 4.2 on 2024-06-12 19:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_remove_user_contact_book_remove_user_hide_email_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumption',
            old_name='liters_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='mileage',
            old_name='last_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='mileage',
            old_name='id_vehicle',
            new_name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, default='images/None/No0img.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 12, 19, 10, 38, 869322, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle_brand'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle_category'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle_type'),
        ),
        migrations.AlterField(
            model_name='vehicle_brand',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.country'),
        ),
        migrations.RemoveField(
            model_name='vehicle_brand',
            name='vehicle_categories',
        ),
        migrations.RemoveField(
            model_name='vehicle_brand',
            name='vehicle_types',
        ),
        migrations.AddField(
            model_name='vehicle_brand',
            name='vehicle_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle_category'),
        ),
        migrations.AddField(
            model_name='vehicle_brand',
            name='vehicle_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle_type'),
        ),
    ]
