# Generated by Django 4.2 on 2024-06-12 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 12, 20, 46, 14, 124111, tzinfo=datetime.timezone.utc)),
        ),
    ]
