# Generated by Django 4.2 on 2024-05-23 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_consumption_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 23, 22, 37, 55, 989225, tzinfo=datetime.timezone.utc)),
        ),
    ]
