# Generated by Django 4.2 on 2024-05-24 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_consumption_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 24, 0, 40, 36, 878990, tzinfo=datetime.timezone.utc)),
        ),
    ]
