# Generated by Django 4.2 on 2024-05-26 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_consumption_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 26, 23, 32, 26, 463233, tzinfo=datetime.timezone.utc)),
        ),
    ]
