# Generated by Django 4.2 on 2024-06-14 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_consumption_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 14, 15, 59, 28, 101891, tzinfo=datetime.timezone.utc)),
        ),
    ]
