# Generated by Django 4.2 on 2024-05-27 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_consumption_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 0, 10, 14, 123294, tzinfo=datetime.timezone.utc)),
        ),
    ]
