# Generated by Django 4.2 on 2024-05-27 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_alter_consumption_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 16, 41, 37, 517689, tzinfo=datetime.timezone.utc)),
        ),
    ]
