# Generated by Django 4.2 on 2024-06-12 19:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_rename_liters_amount_consumption_amount_and_more'),
        ('contact_book', '0003_contact_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2024, 6, 12, 19, 10, 38, 874321, tzinfo=datetime.timezone.utc))),
                ('finish_date', models.DateTimeField(blank=True)),
                ('responsable', models.CharField(max_length=50)),
                ('fail_detected', models.TextField(blank=True, max_length=250)),
                ('mtto_type', models.CharField(choices=[('CORRECTIVO', 'CORRECTIVO'), ('PREVENTIVO', 'PREVENTIVO'), ('PREDICTIVO', 'PREDICTIVO')], default='CORRECTIVO', max_length=15)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Work_order',
                'verbose_name_plural': 'work_orders',
                'db_table': 'work_order',
            },
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_order.work_order')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.workshop')),
            ],
            options={
                'verbose_name': 'Workshops',
                'verbose_name_plural': 'workshops',
                'db_table': 'workshops',
            },
        ),
    ]
