# Generated by Django 4.2 on 2024-06-13 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 18, 15, 48, 231221, tzinfo=datetime.timezone.utc)),
        ),
    ]
