# Generated by Django 4.2 on 2024-06-06 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobil', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'specializations',
                'db_table': 'specialization',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobil', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.city')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.country')),
                ('specialization', models.ManyToManyField(to='contact_book.specialization')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.state')),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'workshops',
                'db_table': 'workshop',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobil', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.state')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'stores',
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobil', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.city')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.country')),
                ('specialization', models.ManyToManyField(to='contact_book.specialization')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.state')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.workshop')),
            ],
            options={
                'verbose_name': 'Mechanic',
                'verbose_name_plural': 'mechanics',
                'db_table': 'mechanic',
            },
        ),
        migrations.CreateModel(
            name='Contact_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.contact')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.mechanic')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_book.workshop')),
            ],
            options={
                'verbose_name': 'Contact_book',
                'verbose_name_plural': 'Contact_books',
                'db_table': 'contact_book',
            },
        ),
    ]
