# Generated by Django 4.2 on 2024-06-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_book', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='contact_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='contact_book.contact_book'),
            preserve_default=False,
        ),
    ]
