# Generated by Django 4.2 on 2024-05-24 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_created_date_alter_user_last_login_and_more'),
        ('contact_book', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobil', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.city')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'stores',
                'db_table': 'store',
            },
        ),
    ]
