# Generated by Django 4.2 on 2024-05-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_created_date_alter_user_last_login_and_more'),
        ('contact_book', '0003_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.state'),
            preserve_default=False,
        ),
    ]
