# Generated by Django 4.2 on 2024-05-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_created_date_alter_user_last_login_and_more'),
        ('contact_book', '0004_contact_country_contact_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.state'),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.city'),
        ),
    ]
