# Generated by Django 4.2 on 2024-05-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_created_date_alter_user_last_login_and_more'),
        ('contact_book', '0005_store_country_store_state_alter_store_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.country'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.state'),
        ),
    ]
