# Generated by Django 4.2 on 2024-05-27 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_created_date_alter_user_last_login_and_more'),
        ('contact_book', '0006_workshop_country_workshop_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.country'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.state'),
        ),
    ]
